name: Continuous Deployment


on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual deployment button appears in GH Actions when dispatch is set.

jobs:
  html_dir_to_gh-pages:
    runs-on: ubuntu-latest
    name: HTML dir to gh-pages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Running the HTML dir to gh-pages Action
        uses: uibcdf/action-html-dir-to-gh-pages@1.0.0
        with:
          branch: main
          html_dir: src
